[tool.poetry]
name = "gridagi"
version = "0.0.0"
description = "fruitloop"
authors = ["Barton Rhodes <barton@plurigrid.art>"]
license = "MIT License"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
openai = "^0.27.2"
pinecone-client = "^2.2.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
